### ISSUE TITLE
Template Review Feedback

### ISSUE THREAD

**Issue by delsonting** [kompassify/kompassify-gtm-template#1]
Thanks for your submission, there is one required and one recommended change. Please update your metadata.yaml file with the new template.tpl hash after updating the template.tpl file:

Required:
Remove the data.gtmOnSuccess(); call on line 56. data.gtmOnSuccess or data.gtmOnFailure should be called exactly once per tag execution. Since the injectScript callback on line 53 will always return data.gtmOnSuccess or data.gtmOnFailure you should not call data.gtmOnSuccess() on line 56.

```
injectScript(url, data.gtmOnSuccess, data.gtmOnFailure, url);

// Call data.gtmOnSuccess when the tag is finished.
data.gtmOnSuccess();
```

Recommended:
Host the instructions in the github readme file rather than a standalone google doc

**Comment by kompassify** [comment]
Fixed after commit 0ad7a2f4b74c432ac04e27b936a6838143484f3a

**Comment by kompassify** [comment]
Thank you for checking our submission, we have made the two changes, please check our submission

**Comment by delsonting** [comment]
Thanks, the template has been approved and should appear in the gallery
within the next day.
